version: "3.6"

services:
  gitlab:
    image: gitlab/gitlab-ce:11.4.8-ce.0
    container_name: gitlab
    hostname: gitlab
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.33.10'
        registry_external_url "http://192.168.33.10:4567"
        gitlab_rails['time_zone'] = 'Asia/Tokyo'
        gitlab_rails['initial_root_password'] = 'password'
        gitlab_rails['initial_shared_runners_registration_token'] = 'token-AABBCCDD'
        unicorn['worker_timeout'] = 60
        unicorn['worker_processes'] = 3
    ports:
      - "8080:80"
    networks:
      infraci_nw:
        ipv4_address: 192.168.33.10
  gitlab-runner-1:
    image: gitlab/gitlab-runner:v11.5.0
    container_name: gitlab-runner-1
    hostname: gitlab-runner-1
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      infraci_nw:
        ipv4_address: 192.168.33.21
  gitlab-runner-2:
    image: gitlab/gitlab-runner:v11.5.0
    container_name: gitlab-runner-2
    hostname: gitlab-runner-2
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      infraci_nw:
        ipv4_address: 192.168.33.22
  gitlab-runner-3:
    image: gitlab/gitlab-runner:v11.5.0
    container_name: gitlab-runner-3
    hostname: gitlab-runner-3
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      infraci_nw:
        ipv4_address: 192.168.33.23

networks:
  infraci_nw:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.33.0/24
